server {
    listen 80;
    server_name mindora.pratiktayde.com;

    resolver 127.0.0.11 ipv6=off;

    location / {
        proxy_pass http://mindora:5000;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

server {
    listen 80;
    server_name immich.pratiktayde.com;

    resolver 127.0.0.11 ipv6=off;

    location = /s/ignite-debugging-promptx/zip {
        alias /mnt/apps/immich/hot/2026-Apr-02/album.zip;

        add_header Content-Type application/zip;
        add_header Content-Disposition 'attachment; filename="ignite-debugging-promptx.zip"';
    }

    location = /s/ignite-inspira-debate/zip {
        alias /mnt/apps/immich/hot/2026-Apr-04/album.zip;

        add_header Content-Type application/zip;
        add_header Content-Disposition 'attachment; filename="ignite-inspira-debate.zip"';
    }   

    location / {
        proxy_pass http://192.168.1.50:30041;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_read_timeout 600;
        proxy_buffering off;
        proxy_request_buffering off;
        chunked_transfer_encoding on;

        send_timeout 600;
        proxy_send_timeout 600;
    }
}